// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9xVJlc6eIkefm-PDsEMibtTC6hVRxb9Y',
    appId: '1:820800717273:web:64a24a9c823deed8c719c8',
    messagingSenderId: '820800717273',
    projectId: 'test-91-d497a',
    authDomain: 'test-91-d497a.firebaseapp.com',
    storageBucket: 'test-91-d497a.firebasestorage.app',
    measurementId: 'G-06YEVVVTBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8MELoVvabMPcp7exz1smogbePU20Bej4',
    appId: '1:820800717273:android:5b64f146e42bdfc0c719c8',
    messagingSenderId: '820800717273',
    projectId: 'test-91-d497a',
    storageBucket: 'test-91-d497a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_WaOlGpVmA2LY_30gN_6eNGZhgrhcLHE',
    appId: '1:820800717273:ios:b73c16bdaac69385c719c8',
    messagingSenderId: '820800717273',
    projectId: 'test-91-d497a',
    storageBucket: 'test-91-d497a.firebasestorage.app',
    iosBundleId: 'com.example.todoFcmApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_WaOlGpVmA2LY_30gN_6eNGZhgrhcLHE',
    appId: '1:820800717273:ios:b73c16bdaac69385c719c8',
    messagingSenderId: '820800717273',
    projectId: 'test-91-d497a',
    storageBucket: 'test-91-d497a.firebasestorage.app',
    iosBundleId: 'com.example.todoFcmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9xVJlc6eIkefm-PDsEMibtTC6hVRxb9Y',
    appId: '1:820800717273:web:e9e030da5a5e799cc719c8',
    messagingSenderId: '820800717273',
    projectId: 'test-91-d497a',
    authDomain: 'test-91-d497a.firebaseapp.com',
    storageBucket: 'test-91-d497a.firebasestorage.app',
    measurementId: 'G-D2PDX8H1GT',
  );
}
